#!/bin/sh

# $HYBRIXD/.git/hooks  => $HYBRIXD
SCRIPTDIR="`dirname \"$0\"`"
REPO="`cd \"$SCRIPTDIR/..\" && pwd`"
HYBRIXD="$REPO/../"
COMMON="$HYBRIXD/common"

sh "$COMMON/scripts/lint/lint.sh" "$REPO" "true"


exit $?
